### ISSUE TITLE
Not working with sequential tasks

### ISSUE THREAD

**Issue by pfdutot** [oar-team/evalys#2]
When working with a .csv file containing only sequential tasks, evalys fails with:

```
Traceback (most recent call last):
  File "/usr/local/bin/evalys", line 9, in <module>
    load_entry_point('evalys==1.0.0.dev0', 'console_scripts', 'evalys')()
  File "/usr/local/lib/python3.5/dist-packages/evalys/evalys.py", line 93, in main
    js = JobSet(inputCSV)
  File "/usr/local/lib/python3.5/dist-packages/evalys/jobset.py", line 31, in __init__
    res_str = row['allocated_processors'].split(' ')
AttributeError: 'int' object has no attribute 'split'
```

This is certainly due to the fact that in this case the last column only contains integer values, and thus is not recognized as a string by python. Changing one allocation from 0 to 0-1 solves the problem.

**Comment by mickours** [comment]
Patch welcomed ;)
